insert into parfum (id, nom, description) values (1, 'Indigo', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into parfum (id, nom, description) values (2, 'Aquamarine', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into parfum (id, nom, description) values (3, 'Mauv', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
insert into parfum (id, nom, description) values (4, 'Pink', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into parfum (id, nom, description) values (5, 'Aquamarine', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into parfum (id, nom, description) values (6, 'Khaki', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into parfum (id, nom, description) values (7, 'Khaki', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into parfum (id, nom, description) values (8, 'Pink', 'Maecenas tincidunt lacus at velit.');
insert into parfum (id, nom, description) values (9, 'Puce', 'Etiam justo. Etiam pretium iaculis justo.');
insert into parfum (id, nom, description) values (10, 'Orange', 'Nulla nisl. Nunc nisl.');
insert into parfum (id, nom, description) values (11, 'Puce', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into parfum (id, nom, description) values (12, 'Yellow', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into parfum (id, nom, description) values (13, 'Aquamarine', 'Quisque porta volutpat erat.');
insert into parfum (id, nom, description) values (14, 'Maroon', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into parfum (id, nom, description) values (15, 'Yellow', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into parfum (id, nom, description) values (16, 'Goldenrod', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into parfum (id, nom, description) values (17, 'Turquoise', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into parfum (id, nom, description) values (18, 'Turquoise', 'In quis justo.');
insert into parfum (id, nom, description) values (19, 'Teal', 'Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into parfum (id, nom, description) values (20, 'Crimson', 'Aliquam erat volutpat.');
insert into parfum (id, nom, description) values (21, 'Indigo', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into parfum (id, nom, description) values (22, 'Crimson', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into parfum (id, nom, description) values (23, 'Blue', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into parfum (id, nom, description) values (24, 'Khaki', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into parfum (id, nom, description) values (25, 'Pink', 'Duis aliquam convallis nunc.');
